language: objective-c
osx_image: xcode9.2
env:
  - EARLY_START_SIMULATOR=1 # early starting simulator reduces false negatives due to test timeouts
before_install:
  - gem install xcpretty
script: travis_retry
notifications:
  slack: 
    csgospectator:Ks30AV0jrUu1cGITVle9WReD
    on_success: always
    on_failure: always
    on_start: never
  email: false
