disabled_rules: # rule identifiers to exclude from running
- line_length
- trailing_whitespace
# Find all the available rules by running:
# swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
